spring:
  application:
    name: demo
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      format_sql: true      # 讓 SQL 換行排版（你原本這行放錯位置了，要放在 properties 內）
      highlight_sql: true   # 讓 SQL 在 Console 變彩色
      use_sql_comments: true # 在 SQL 前顯示是哪個 Method 觸發的
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-wait: 5000
  web: 
    resources.add-mappings: false
  devtools:
    restart:
      enabled: true
      poll-interval: 1000
      quiet-period: 400
  flyway:
      baseline-on-migrate: true

logging:
  level:
    org.hibernate.SQL: debug           # 顯示 SQL
    org.hibernate.orm.jdbc.bind: trace # 顯示 ? 綁定的參數數值 (最重要！)
  file:
    name: logs/app.log

server:
  port: 8080

jwt:
  secret: X1a9Q7lRkpZExmFhC/Y1m+P1YrRm+0HvZkQ4L4bRuEk=

